### ISSUE TITLE
B9 dependency.

### ISSUE THREAD

**Issue by martinezfg11** [WolfairCorp/AoA-Technologies#3]
I believe I removed all the B9 dependencies. If not, I think it would help to get rid of those and replace them with ASET props.

**Comment by WolfairCorp** [comment]
Ok.

**Comment by WolfairCorp** [comment]
You shouldn't base yourself on your repo: it didnt merged correctly (I've changed the folder structure). Just in case.

**Comment by martinezfg11** [comment]
Understood.

**Comment by WolfairCorp** [comment]
While updating I re-changed the engine FX to a stock one, so no more dependency this side.
Still finding HotRockets blue FX better.

**Comment by martinezfg11** [comment]
I see, I wasn't aware the B9 dependency was due to the engine FX. Maybe it can be absorbed into the mod with permission?

**Comment by WolfairCorp** [comment]
Ah, so this wasn't a prop dependency?

**Comment by WolfairCorp** [comment]
Please confirm, I'll close this issue.

**Comment by martinezfg11** [comment]
Right, there is no B9 Prop dependency.

**Comment by WolfairCorp** [comment]
Perfect
